apiVersion: apps/v1
kind: Deployment
metadata:
  name: tilt-site
spec:
  selector:
    matchLabels:
      app: tilt-site
  template:
    metadata:
      labels:
        app: tilt-site
    spec:
      containers:
      - name: tilt-site
        image: tilt-site
        ports:
        - containerPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-site
spec:
  selector:
    matchLabels:
      app: docs-site
  template:
    metadata:
      labels:
        app: docs-site
    spec:
      containers:
      - name: docs-site
        image: docs-site
        ports:
        - containerPort: 4000
