---
title: Use Docker Compose
description: Use Tilt to launch services from a Compose file
code: |
  docker_compose('./docker-compose.yml')
tags:
- docker
- docker_compose
release_stage: released
link:
  title: "API: docker_compose()"
  href: "/api.html#api.docker_compose"
