---
title: Deploy Docker Compose services with overrides
description: Layer overrides on top of an existing Compose file
code: |
  services = {'app': {'environment': {'DEBUG': 'true'}}}
  docker_compose(['docker-compose.yml', encode_yaml({'services': services})])
tags:
- docker
- docker_compose
release_stage: released
link:
  title: "API: docker_compose()"
  href: "/api.html#api.docker_compose"
