---
title: Build and deploy with Docker Compose
description: Launch services using an existing Compose file
code: |
  docker_compose('./docker-compose.yml')
tags:
- docker
- docker_compose
release_stage: released
link:
  title: "API: docker_compose()"
  href: "/api.html#api.docker_compose"
