---
title: Create a K8s deployment
description: Deploy a redis server with the "deployment" extension
code: |
  # Load the 'deployment' extension
  load('ext://deployment', 'deployment_create')
  # Create a redis deployment and service with a readiness probe
  deployment_create(
    'redis',
    ports='6379',
    readiness_probe={'exec':{'command':['redis-cli','ping']}}
  )
tags:
- k8s
- deployment
- extensions
release_stage: released
link:
  title: "Extension: deployment"
  href: https://github.com/tilt-dev/tilt-extensions/tree/master/deployment
