---
title: Create a K8s resource from existing objects
description: Make a new resource by grouping objects necessary for cluster setup
code: |
  k8s_resource(
    objects=['my-ns:namespace', 'kafka:crd', 'some-ingress:ingress'],
    new_name='cluster-setup',
  )
  # Wait to deploy this resource until cluster setup is complete
  k8s_resource('myapp', resource_deps=['cluster-setup'])
tags:
- k8s
- k8s_resource
release_stage: released
link:
  title: "Tiltfile Concepts: Configuring K8s Resources"
  href: "/tiltfile_concepts.html#configuring-kubernetes-resources"
