title: Tilt
email: hi@tilt.dev
description: >-
  Local Kubernetes development with no stress
baseurl: ""
url: "https://docs.tilt.dev/"
docsurl: "https://docs.tilt.dev/"
landingurl: "https://tilt.dev/"
blogurl: "https://blog.tilt.dev/"
twitter_username: tilt_dev
github_username:  windmilleng
google_analytics: UA-129150759-2
include:
  - _redirects

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-inline-svg
