title: Tilt
email: hi@windmill.engineering
description: >-
  Local Kubernetes development with no stress
baseurl: ""
url: "https://docs.tilt.build/"
docsurl: "https://docs.tilt.build/"
landingurl: "https://tilt.build/"
twitter_username: windmill_eng
github_username:  windmilleng
google_analytics: UA-129150759-2

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-inline-svg
